# Generated by Django 3.0.5 on 2021-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='que_category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Technology', 'Technology'), ('Products', 'Products'), ('Science', 'Science'), ('Bussiness', 'Bussiness'), ('Educations', 'Educations'), ('GK', 'GK'), ('Space', 'Space'), ('Health', 'Health'), ('Others', 'Others')], default='Others', max_length=30),
        ),
    ]
