# Generated by Django 3.0.5 on 2021-05-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20210528_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='que_details',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
