# Generated by Django 3.0.5 on 2021-05-29 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0004_questionsmodel_que_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionsmodel_parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
