# Generated by Django 3.0.5 on 2021-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0010_auto_20210601_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='que_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
