# Generated by Django 3.0.5 on 2021-06-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0011_questionsmodel_que_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='que_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
