# Generated by Django 3.0.5 on 2021-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0012_auto_20210602_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersmodel',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
