# Generated by Django 3.0.5 on 2021-06-03 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0013_auto_20210603_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersmodel',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='answersmodel',
            name='ans_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='answersmodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='ans_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
