# Generated by Django 3.0.5 on 2021-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0016_auto_20210603_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='anslikesmodel',
            name='like_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
