# Generated by Django 3.0.5 on 2021-06-04 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0017_anslikesmodel_like_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersmodel',
            name='likes',
            field=models.ManyToManyField(related_name='answers_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnsLikesModel',
        ),
    ]
