# Generated by Django 3.0.5 on 2021-06-07 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0021_auto_20210607_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
