# Generated by Django 3.0.5 on 2021-06-07 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0022_auto_20210607_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='followed_to',
            field=models.ManyToManyField(related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
