# Generated by Django 3.0.5 on 2021-06-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0023_auto_20210607_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
