# Generated by Django 3.0.5 on 2021-06-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0025_auto_20210607_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='card_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='followers',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
