# Generated by Django 3.0.5 on 2021-06-18 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0026_auto_20210608_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='card_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
