# Generated by Django 3.0.5 on 2021-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0027_auto_20210618_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='got_ans',
            field=models.BooleanField(default=False),
        ),
    ]
