# Generated by Django 3.0.5 on 2021-06-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0028_questionsmodel_got_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='got_ans',
        ),
    ]
