# Generated by Django 3.0.5 on 2021-05-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_auto_20210522_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
