# Generated by Django 3.0.5 on 2021-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0004_auto_20210526_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(blank=True, default='./static/images/default_avtar.png', null=True, upload_to='profile/images'),
        ),
    ]
