# Generated by Django 3.0.5 on 2021-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0009_auto_20210526_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(default='/static/images/default_profile.png', upload_to='profile/images'),
        ),
    ]
