# Generated by Django 3.0.5 on 2021-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0014_auto_20210530_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile/images/default_profile.png', null=True, upload_to='profile/images'),
        ),
    ]
