# Generated by Django 3.0.5 on 2021-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0015_auto_20210606_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
