# Generated by Django 3.0.5 on 2021-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0016_usermodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='points_update',
            field=models.CharField(default='', max_length=12),
        ),
    ]
