# Generated by Django 3.0.5 on 2021-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0017_usermodel_points_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='points_update',
            field=models.CharField(default='not_updated', max_length=12),
        ),
    ]
