# Generated by Django 3.0.5 on 2021-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0018_auto_20210618_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ans_point',
            field=models.BooleanField(default=False),
        ),
    ]
