# Generated by Django 3.0.5 on 2021-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0019_usermodel_ans_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
