# Generated by Django 3.0.5 on 2021-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0021_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OtpModel',
        ),
    ]
